#!/bin/bash

set -e

cd $(dirname "$0")

if [[ "$1" == "deploy" ]]; then
  if [ -z "$2" ]; then
    echo "Usage: sitectl deploy [keyfile]"
    exit 0;
  fi

  ./sitectl clean
  ./sitectl build

  ssh -i $2 push@master.cdn.funcptr.org "mkdir -p /srv/cdn/funcptr.org"
  rsync -e "ssh -i $2" -a _site/ push@master.cdn.funcptr.org:/srv/cdn/funcptr.org/
  exit 0;
fi

cabal run --ghc-options=-dynamic funcptr-org $@
